### ISSUE TITLE
Triển khai Nextcloud High Availability trên Docker Swarm - Clean Installation

### ISSUE THREAD

**Issue by codename477** [codename477/nextcloud-docker-cluster#2]
# Triển khai Nextcloud High Availability trên Docker Swarm

## 🎯 Mục tiêu
Triển khai lại hoàn toàn Nextcloud HA trên Docker Swarm với PostgreSQL Primary/Replica, monitoring cơ bản và tích hợp F5 Load Balancer.

### Cluster Information
- **Manager Node**: NextcloudCluster (10.202.1.166)
- **Worker Nodes**: 
  - NextcloudNode1 (10.202.1.163) - PostgreSQL Primary
  - NextcloudNode2 (10.202.1.164) - PostgreSQL Replica  
  - NextcloudNode3 (10.202.1.165) - Worker Services
- **Domain**: docs.qtsc.com.vn
- **F5 Load Balancer**: 210.2.92.21:443 (SSL termination)
- **NFS Server**: 172.28.10.129 (/mnt/nextcloud-data)

### BƯỚC 1: Dọn dẹp môi trường (Thực hiện trên Manager Node)

```bash
# Kết nối SSH đến NextcloudCluster (10.202.1.166)
ssh root@10.202.1.166

# Stop và remove tất cả services hiện tại
docker service ls
docker stack rm nextcloud 2>/dev/null || true
docker service rm $(docker service ls -q) 2>/dev/null || true

# Chờ services dừng hoàn toàn
sleep 30

# Remove networks (giữ lại ingress và docker_gwbridge)
docker network rm nextcloud_backend nextcloud_frontend astra_net 2>/dev/null || true

# Remove volumes cũ trên tất cả nodes
docker volume rm nextcloud_data nextcloud_stack_nextcloud_data 2>/dev/null || true
```

### BƯỚC 2: Dọn dẹp dữ liệu NFS (Thực hiện trên các Worker Nodes)

```bash
# Trên NextcloudNode1 (10.202.1.163)
ssh root@10.202.1.163
sudo rm -rf /mnt/nextcloud-data/*
sudo mkdir -p /mnt/nextcloud-data/{nextcloud_aio_apache,nextcloud_aio_database,nextcloud_aio_database_dump,nextcloud_aio_nextcloud,nextcloud_aio_redis,nextcloud_aio_database_replica}
sudo chmod -R 777 /mnt/nextcloud-data/

# Trên NextcloudNode2 (10.202.1.164)
ssh root@10.202.1.164
sudo rm -rf /mnt/nextcloud-data/*
sudo mkdir -p /mnt/nextcloud-data/{nextcloud_aio_apache,nextcloud_aio_database,nextcloud_aio_database_dump,nextcloud_aio_nextcloud,nextcloud_aio_redis,nextcloud_aio_database_replica}
sudo chmod -R 777 /mnt/nextcloud-data/

# Trên NextcloudNode3 (10.202.1.165)
ssh root@10.202.1.165
sudo rm -rf /mnt/nextcloud-data/*
sudo mkdir -p /mnt/nextcloud-data/{nextcloud_aio_apache,nextcloud_aio_database,nextcloud_aio_database_dump,nextcloud_aio_nextcloud,nextcloud_aio_redis,nextcloud_aio_database_replica}
sudo chmod -R 777 /mnt/nextcloud-data/
```

### BƯỚC 3: Tạo secrets (Thực hiện trên Manager Node)

```bash
# Quay lại NextcloudCluster
ssh root@10.202.1.166

# Tạo password secrets
echo "7Aw4O%?Ah6*N" | docker secret create database_password -
echo "7Aw4O%?Ah6*N" | docker secret create redis_password -
echo "7Aw4O%?Ah6*N" | docker secret create nextcloud_password -
echo "7Aw4O%?Ah6*N" | docker secret create onlyoffice_secret -
echo "7Aw4O%?Ah6*N" | docker secret create collabora_secret -
echo "7Aw4O%?Ah6*N" | docker secret create turn_secret -
echo "7Aw4O%?Ah6*N" | docker secret create signaling_secret -
echo "7Aw4O%?Ah6*N" | docker secret create recording_secret -
echo "7Aw4O%?Ah6*N" | docker secret create imaginary_secret -
echo "7Aw4O%?Ah6*N" | docker secret create whiteboard_secret -
echo "7Aw4O%?Ah6*N" | docker secret create talk_internal_secret -
echo "7Aw4O%?Ah6*N" | docker secret create fulltextsearch_password -

# Verify secrets
docker secret ls
```

### BƯỚC 4: Tạo networks

```bash
# Tạo overlay networks
docker network create --driver overlay --attachable nextcloud_frontend
docker network create --driver overlay --attachable nextcloud_backend

# Verify networks
docker network ls
```

### BƯỚC 5: Tạo file docker-compose.yml

```yaml
# File: /root/nextcloud-ha/docker-compose.yml
version: '3.8'

services:
  # PostgreSQL Primary Database
  nextcloud-aio-database-primary:
    image: postgres:15-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nfs == true
          - node.hostname == NextcloudNode1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    environment:
      POSTGRES_DB: nextcloud_database
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      PGUSER: nextcloud
    secrets:
      - database_password
    volumes:
      - /mnt/nextcloud-data/nextcloud_aio_database:/var/lib/postgresql/data
    networks:
      - nextcloud_backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud_database"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL Replica Database  
  nextcloud-aio-database-replica:
    image: postgres:15-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nfs == true
          - node.hostname == NextcloudNode2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    environment:
      PGUSER: replica
      POSTGRES_DB: nextcloud_database
      POSTGRES_USER: replica
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_MASTER_SERVICE: nextcloud-aio-database-primary
    secrets:
      - database_password
    volumes:
      - /mnt/nextcloud-data/nextcloud_aio_database_replica:/var/lib/postgresql/data
    networks:
      - nextcloud_backend
    depends_on:
      - nextcloud-aio-database-primary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U replica"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Cache
  nextcloud-aio-redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nfs == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    command: redis-server --requirepass "7Aw4O%?Ah6*N" --appendonly yes
    volumes:
      - /mnt/nextcloud-data/nextcloud_aio_redis:/data
    networks:
      - nextcloud_backend
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "7Aw4O%?Ah6*N", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nextcloud Application
  nextcloud-aio-nextcloud:
    image: nextcloud:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.nfs == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    environment:
      POSTGRES_HOST: nextcloud-aio-database-primary
      POSTGRES_PORT: 5432
      POSTGRES_DB: nextcloud_database
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: "7Aw4O%?Ah6*N"
      REDIS_HOST: nextcloud-aio-redis
      REDIS_HOST_PASSWORD: "7Aw4O%?Ah6*N"
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: "7Aw4O%?Ah6*N"
      NEXTCLOUD_TRUSTED_DOMAINS: docs.qtsc.com.vn
      OVERWRITEHOST: docs.qtsc.com.vn
      OVERWRITEPROTOCOL: https
      OVERWRITECONDADDR: ^10\.202\.1\.(163|164|165)$
      TRUSTED_PROXIES: 10.202.1.0/24 172.0.0.0/8 210.2.92.21
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_LIMIT: 16G
      NEXTCLOUD_DATA_DIR: /var/www/html/data
    volumes:
      - /mnt/nextcloud-data/nextcloud_aio_nextcloud:/var/www/html
    networks:
      - nextcloud_backend
      - nextcloud_frontend
    depends_on:
      - nextcloud-aio-database-primary
      - nextcloud-aio-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Apache Web Server
  nextcloud-aio-apache:
    image: nginx:alpine
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.nfs == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/nextcloud-data/nextcloud_aio_apache:/etc/nginx/conf.d
      - /mnt/nextcloud-data/nextcloud_aio_nextcloud:/var/www/html:ro
    networks:
      - nextcloud_frontend
      - nextcloud_backend
    depends_on:
      - nextcloud-aio-nextcloud
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # OnlyOffice Document Server
  nextcloud-aio-onlyoffice:
    image: onlyoffice/documentserver:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nfs == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "7Aw4O%?Ah6*N"
      JWT_HEADER: AuthorizationJwt
    networks:
      - nextcloud_backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/welcome/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 180s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Monitoring và Health Check
  nextcloud-healthcheck:
    image: curlimages/curl:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
    command: >
      sh -c "
      while true; do
        echo '[HEALTHCHECK]' $(date): 'Checking Nextcloud services...'
        curl -f http://nextcloud-aio-apache/ || echo '[ERROR] Apache unhealthy'
        curl -f http://nextcloud-aio-nextcloud/status.php || echo '[ERROR] Nextcloud unhealthy'
        sleep 300
      done"
    networks:
      - nextcloud_frontend
      - nextcloud_backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  database_password:
    external: true
  redis_password:
    external: true
  nextcloud_password:
    external: true
  onlyoffice_secret:
    external: true
  collabora_secret:
    external: true
  turn_secret:
    external: true
  signaling_secret:
    external: true
  recording_secret:
    external: true
  imaginary_secret:
    external: true
  whiteboard_secret:
    external: true
  talk_internal_secret:
    external: true
  fulltextsearch_password:
    external: true

networks:
  nextcloud_frontend:
    external: true
  nextcloud_backend:
    external: true
```

### BƯỚC 6: Tạo cấu hình nginx

```bash
# Tạo thư mục cấu hình
mkdir -p /root/nextcloud-ha/configs

# Tạo nginx config
cat > /root/nextcloud-ha/configs/default.conf << 'EOF'
upstream nextcloud {
    server nextcloud-aio-nextcloud:80;
}

server {
    listen 80;
    server_name docs.qtsc.com.vn;
    
    # Security headers
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    add_header Referrer-Policy no-referrer;
    
    # Remove X-Powered-By
    fastcgi_hide_header X-Powered-By;
    
    # Path to the root of your installation
    root /var/www/html;
    index index.php index.html /index.php$request_uri;
    
    # Rule borrowed from `.htaccess` to handle Microsoft DAV clients
    location = / {
        if ( $http_user_agent ~ ^DavClnt ) {
            return 302 /remote.php/webdav/$is_args$args;
        }
    }
    
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    
    # Make a regex exception for `/.well-known` so that clients can still
    # access it despite the existence of the regex rule
    location ^~ /.well-known {
        location = /.well-known/carddav { return 301 /remote.php/dav/; }
        location = /.well-known/caldav  { return 301 /remote.php/dav/; }
        location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
        location /.well-known/pki-validation    { try_files $uri $uri/ =404; }
        return 301 /index.php$request_uri;
    }
    
    # Rules borrowed from `.htaccess` to hide certain paths
    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/)  { return 404; }
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console)                { return 404; }
    
    # Ensure this block, which passes PHP files to the PHP process, is above the blocks
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;
        
        try_files $fastcgi_script_name =404;
        
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;
        
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass nextcloud;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
        
        fastcgi_max_temp_file_size 0;
        fastcgi_buffering off;
    }
    
    location ~ \.(?:css|js|svg|gif|png|jpg|ico|wasm|tflite|map)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=15778463, immutable";
        access_log off;
    }
    
    location ~ \.woff2?$ {
        try_files $uri /index.php$request_uri;
        expires 7d;
        access_log off;
    }
    
    # Rule borrowed from `.htaccess`
    location /remote {
        return 301 /remote.php$request_uri;
    }
    
    location / {
        try_files $uri $uri/ /index.php$request_uri;
    }
}
EOF
```

### BƯỚC 7: Deploy stack

```bash
# Tạo thư mục project
mkdir -p /root/nextcloud-ha
cd /root/nextcloud-ha

# Copy nginx config vào NFS
ssh root@10.202.1.163 "mkdir -p /mnt/nextcloud-data/nextcloud_aio_apache"
scp /root/nextcloud-ha/configs/default.conf root@10.202.1.163:/mnt/nextcloud-data/nextcloud_aio_apache/
scp /root/nextcloud-ha/configs/default.conf root@10.202.1.164:/mnt/nextcloud-data/nextcloud_aio_apache/
scp /root/nextcloud-ha/configs/default.conf root@10.202.1.165:/mnt/nextcloud-data/nextcloud_aio_apache/

# Deploy stack
docker stack deploy -c docker-compose.yml nextcloud

# Monitor deployment
watch -n 5 'docker service ls'
```

### BƯỚC 8: Kiểm tra và xác minh

```bash
# Kiểm tra services
docker service ls
docker stack ps nextcloud

# Kiểm tra logs
docker service logs nextcloud_nextcloud-aio-database-primary
docker service logs nextcloud_nextcloud-aio-nextcloud
docker service logs nextcloud_nextcloud-aio-apache

# Test kết nối
curl -I http://docs.qtsc.com.vn

# Kiểm tra database connectivity
docker exec -it $(docker ps -q -f name=nextcloud_nextcloud-aio-database-primary) psql -U nextcloud -d nextcloud_database -c "SELECT version();"

# Kiểm tra Redis
docker exec -it $(docker ps -q -f name=nextcloud_nextcloud-aio-redis) redis-cli -a "7Aw4O%?Ah6*N" ping
```

### Log Collection
```bash
# Setup log monitoring script
cat > /root/nextcloud-monitoring.sh << 'EOF'
#!/bin/bash
echo "=== NEXTCLOUD HA MONITORING ===" 
echo "Timestamp: $(date)"
echo ""
echo "=== DOCKER SERVICES STATUS ==="
docker service ls
echo ""
echo "=== STACK STATUS ==="
docker stack ps nextcloud --no-trunc
echo ""
echo "=== DATABASE PRIMARY HEALTH ==="
docker service logs --tail 5 nextcloud_nextcloud-aio-database-primary 2>/dev/null || echo "Service not found"
echo ""
echo "=== DATABASE REPLICA HEALTH ==="
docker service logs --tail 5 nextcloud_nextcloud-aio-database-replica 2>/dev/null || echo "Service not found"
echo ""
echo "=== NEXTCLOUD APPLICATION HEALTH ==="
docker service logs --tail 5 nextcloud_nextcloud-aio-nextcloud 2>/dev/null || echo "Service not found"
echo ""
echo "=== APACHE WEB SERVER HEALTH ==="
docker service logs --tail 5 nextcloud_nextcloud-aio-apache 2>/dev/null || echo "Service not found"
echo ""
echo "=== NFS MOUNT STATUS ==="
df -h /mnt/nextcloud-data 2>/dev/null || echo "NFS not mounted"
echo ""
echo "========================================="
EOF

chmod +x /root/nextcloud-monitoring.sh

# Setup cron for monitoring
(crontab -l 2>/dev/null; echo "*/5 * * * * /root/nextcloud-monitoring.sh >> /var/log/nextcloud-monitoring.log 2>&1") | crontab -
```

### Common Issues
1. **Service không start**: Kiểm tra node labels và constraints
2. **Database connection issues**: Verify secrets và network connectivity  
3. **NFS mount issues**: Kiểm tra quyền và mount points
4. **F5 connectivity**: Verify port 80/443 accessibility

### Emergency Commands
```bash
# Restart toàn bộ stack
docker stack rm nextcloud && sleep 30 && docker stack deploy -c docker-compose.yml nextcloud

# Scale services
docker service scale nextcloud_nextcloud-aio-nextcloud=3

# Update service
docker service update --image nextcloud:latest nextcloud_nextcloud-aio-nextcloud
```

## 📋 Post-deployment Checklist

- [ ] Tất cả services running và healthy
- [ ] Database primary/replica connectivity
- [ ] Web interface accessible via F5
- [ ] File upload/download functionality  
- [ ] OnlyOffice document editing
- [ ] Log collection working
- [ ] Backup strategy implemented
- [ ] Monitoring alerts configured

## 🔐 Security Hardening

- Passwords được quản lý qua Docker secrets
- Network segmentation với overlay networks
- Container security với read-only filesystems
- Resource limits để tránh resource exhaustion
- Structured logging cho SIEM integration
- Regular security updates schedule
